### PR TITLE
Organize exception variables, and update authorship affected changes to avoid RepoSense issues

### PR DESCRIPTION
**Pull request by chydarren**
This pull request seeks to remove redundant / unused exception variables. It also updates the names of some exception variables and classes that are used across multiple types of commands or purpose. To avoid RepoSense issues, authorship has been credited to different authors on the affected files.

### CODE REVIEW

**Review by wcwy — COMMENTED** [review]
LGTM

**Review by brian-vb — APPROVED** [review]
All looks good to me!

**Review by chinhan99 — APPROVED** [review]
Updates look good.

**Review by paullowse — APPROVED** [review]

**Comment by paullowse** [comment]
lgtm!!

**Pull request merged**
